import AddNewWorkout from "@/components/AddNewWorkoutForm";
import Head from "next/head";

export default function AddNewWorkoutPage() {
  function handleSubmit(e) {
    e.preventDefault();

    console.log("submitted");
  }

  return (
    <>
      <Head>
        <title>Add a new Workout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AddNewWorkout onSubmit={handleSubmit} />
      </main>
    </>
  );
}
