import Head from "next/head";
import { Inter } from "@next/font/google";
import Link from "next/link";
import { useAtom } from "jotai";
import { workoutAtom } from "@/lib/db";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [workouts, setWorkouts] = useAtom(workoutAtom);

  return (
    <>
      <Head>
        <title>Workouts.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul>
          {workouts.map(
            ({ name, description, sets, repetitions, duration, breaktime }) => {
              return (
                <li key={name}>
                  <article>
                    <h2>{name}</h2>
                    {description ? <p>{description}</p> : ""}
                    <p>{sets} Set(s)</p>
                    <p>
                      {repetitions} Repetition(s) á {duration} Seconds
                    </p>
                    <p>{breaktime} Seconds Break in between</p>
                    <Link href="/details/id" passHref legacyBehavior>
                      <a>Show Details</a>
                    </Link>
                  </article>
                </li>
              );
            }
          )}
        </ul>
      </main>
    </>
  );
}
