import Head from "next/head";
import { Inter } from "@next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Workouts.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul>
          <li>
            <article>
              <h2>Hangboard 20mm hang</h2>
              <p>1 Set(s)</p>
              <p>3 Repetition(s) á 10 Seconds</p>
              <p>2 Minute(s) Break in between</p>
              <Link href={`/details/id`}>Click to Edit/Show Details</Link>
            </article>
          </li>
          <li>
            <article>
              <h2>Pull-Up</h2>
              <p>3 Set(s)</p>
              <p>3 Repetition(s)</p>
              <p>2 Minute(s) Break in between</p>
            </article>
          </li>
        </ul>
      </main>
    </>
  );
}
