import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Training App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Workouts.</h1>
      </header>
      <main className={styles.main}>
        <nav>
          <Link href="/workouts">Workouts</Link>
          <Link href="/addWorkout">Add new Workout</Link>
          <Link href="/profile">Profile</Link>
          <Link href="/settings">Settings</Link>
        </nav>
        <ul>
          <li>
            <article>
              <h2>Hangboard 20mm hang</h2>
              <image />
              <p>1 Set(s)</p>
              <p>3 Repetition(s) á 10 Seconds</p>
              <p>2 Minute(s) Break in between</p>
            </article>
          </li>
          <li>
            <article>
              <h2>Pull-Up</h2>
              <p>3 Set(s)</p>
              <p>3 Repetition(s)</p>
              <p>2 Minute(s) Break in between</p>
            </article>
          </li>
        </ul>
        <form aria-labelledby="addNewWorkout">
          <h3 id="addNewWorkout">Add new Workout</h3>
          <label htmlFor="name">Name</label>
          <input id="name" name="name"></input>
          <label htmlFor="sets">Amount of Sets</label>
          <input id="sets" type="number" name="sets"></input>
          <label htmlFor="reps">Amount of Repetitions</label>
          <input id="reps" type="number" name="reps"></input>
          <label htmlFor="duration">Duration</label>
          <input id="duration" type="number" name="duration"></input>
          <label htmlFor="break">Duration of Break</label>
          <input id="break" type="number" name="break"></input>
          <button type="submit">Submit</button>
        </form>
      </main>
    </>
  );
}
